### ISSUE TITLE
Stick Poe A - wired network connection buggy

### ISSUE THREAD

**Issue by trantoriana** [allexoK/Esp32-Stick-Boards-Docs#2]
Hi,

Gotten my two esp32-stick-poe-a today and having trouble getting a stable wired connection.

The moment I boot from Poe, the network does come up but seems very very unstable. The green network led rapidly flashes. I took the esphome example from the one In the code here.

Any pointer what could be the issue or how I could go about finding what is going on?

Esphome is 2023.09 or what ever latest version is.

Thanks, trant

**Comment by allexoK** [comment]
Hi trant, 
have you tested both boards? Have you tried pinging the boards? Is the ping consistent or are there any issues?
Aleks

**Comment by allexoK** [comment]
Hi @trantoriana, how it it going? Have you managed to get it working? If so, what was the problem?

**Comment by trantoriana** [comment]
Hi AlexoK,Thanks for asking.Unfortunately one of the devices went up in smoke. Literally... for whatever reason, the second one does seem to get an IP address... Most of the times, but connectivity ix extremely bad and unreliable. Probably because it is doing something with the switch given the flashing green light.My switch is a ubiquity Poe. Poe standards are tricky and they might not be compatible.I gave up on the modules to be honest and returned to the olimex Poe iso, which works instantaneously.Thanks, Trant On 13 Oct 2023 12:10, allexoK ***@***.***> wrote:
Hi @trantoriana, how it it going? Have you managed to get it working? If so, what was the problem?

**Comment by allexoK** [comment]
I am very sorry to hear that, would you be so kind as to provide the switch model number? I would really like to try to replicate this problem, or at least warn people of incompatibility with this switch. Thank you very much for your feedback!

**Comment by trantoriana** [comment]
*) Ubiquity USW pro 24 POEhttps://eu.store.ui.com/eu/en/products/usw-pro-24-poeThat is the switch.I had the same problem with a ubiquity Poe injector. Good luck.TrantOn 14 Oct 2023 14:20, allexoK ***@***.***> wrote:
I am very sorry to hear that, would you be so kind as to provide the switch model number? I would really like to try to replicate this problem, or at least warn people of incompatibility with this switch. Thank you very much for your feedback!

**Comment by allexoK** [comment]
I have updated the README file with troubleshooting and PoE compatibility sections. Perhaps it can help other people if they experience the same issue.
