### ISSUE TITLE
Not an issue : easyeda source

### ISSUE THREAD

**Issue by nliaudat** [allexoK/Esp32-Stick-Boards-Docs#3]
Hi, 

Many thanks for your work !

I'm working on several projects that really needs your help, or easyeda sources for your obvious project. 

For example https://github.com/jomjol/AI-on-the-edge-device would need an identical card (latest with cam), but with an sd card and several backlight LEDs. 

One of my projects (https://github.com/nliaudat/esp32_8ch_motor_shield) would need PoE and probably an Esp32 card soldered directly. 

I can adapt things on easyeda, but it's a very hard task to recreate everything and find the good parts. So, would it be possible to get your support ? (or easyeda source)

Best regards
Nicolas

**Comment by allexoK** [comment]
Hello Nicolas,
thanks for your projects too!
Actually https://github.com/jomjol/AI-on-the-edge-device inspired me to make this board https://hackaday.io/project/193356-esp32-stick-camesp32-s3activepassivepoecamera :) (I will have more of them in stock within a couple of weeks.) It has backlight leds, but no SD card unfortunately... I can adapt it to your needs, but I don't want to share the source. Can you write me an email to alexok997@gmail.com, and we can discuss the details?
Best regards,
Alex
