### ISSUE TITLE
Question about turning of the white power LED

### ISSUE THREAD

**Issue by leonnicklas** [allexoK/Esp32-Stick-Boards-Docs#4]
Hi there!

Thanks for your great work, I'm looking forward to using your boards in my motorhome!

One question though:
Is there any way to programmatically turn off the power LED?

The problem is that I'm using it in an off-grid system, where I naturally want to save power wherever I can.
Also, the board will be mounted behind walls and therefore the LED can't be seen anyway...

Would love to hear from you:)

Kind regards
Leon (from Munich)

**Comment by allexoK** [comment]
Hello Leon,
thanks! 
Unfortunately, there is no way to disable the power LED via SW. To do it 'via hardware' there are 3 options:
- Unsolder the Led itself
- Unsolder the Led resistor
- Cut the led power trace with a knife(I usually use utility knife, the board is two layer, so it's not possible to damage the hidden internal layers)

Here are parts/traces locations for different board types:

### Esp32-Stick-PoE-A

![tracecut-esp32stickpoea](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/d7b599da-8dcd-4f60-bb59-f4a60c80fdd2)
![led-esp32stickpoea](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/599b5110-5ec9-4e5e-8f4b-f9e70a7e4b6a)
![res-esp32stickpoea](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/a150cb17-7759-4341-a18d-11840cc76de1)
![trace-esp32stickpoea](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/920654ad-2198-41e3-85e7-dbac3b4115d8)
 
### Esp32-Stick-Eth

![tracecut-esp32sticketh](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/eeeb6e94-7983-4f9a-acb2-62c0a00fc9cd)
![res-esp32sticketh](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/2553372d-ebb9-43f6-a0fc-a875062c3eec)
![led-esp32sticketh](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/7d6ae4c4-4d66-4b7d-b798-f3241435980e)
![trace-esp32sticketh](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/0c7e4819-308a-413a-935e-5fb1072ce52f)

### Esp32-Stick-PoE-P

![tracecut-esp32stickpoep](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/092bf44c-8310-448e-a09e-46c74b327b36)
![led-esp32stickpoep](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/d287c76e-21dc-41dd-af25-cd28edd2e664)
![res-esp32stickpoep](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/750bdd4a-9602-48a4-bb71-c46fb0e4fada)
![trace-esp32stickpoep](https://github.com/allexoK/Esp32-Stick-Boards-Docs/assets/50021377/82831f63-dd7a-4438-aba1-a63c73587e9d)

Best regards and good luck with your motorhome project!
Alex

**Comment by leonnicklas** [comment]
@allexoK thanks for the very detailed explanation! I will look into it and decide which option is best for me:)
