### ISSUE TITLE
Feature request: Provide 3D models as STEP files

### ISSUE THREAD

**Issue by kagehisa** [allexoK/Esp32-Stick-Boards-Docs#5]
I'm not very talented when it comes to 3d modelling, but when I do use an opensource or other free alternative to a 3d CAD tool, they almost never support the import of an `.obj` with the corresponding material file. It is mostly `.obj` only. FreeCAD is such an example. But what almost all tools support is the import of a `.step` file, this includes PCB tools which use the models to provide a 3d preview. 

Would it be possible to provide the 3d models as `STEP` files in addition to the `.obj` files?

**Comment by allexoK** [comment]
Hi @kagehisa, thanks for reaching out! I have just pushed them to the repository, online step file viewer shows them without problem so I hope they are ok.

**Comment by kagehisa** [comment]
Thanks a lot @allexoK ! I just tested them in FreeCAD and as a model resource in KiCAD. In both cases they just work fine. 
Thank you again for the quick response and upload of the ste files!
