### ISSUE TITLE
Question about direct access to PoE power 

### ISSUE THREAD

**Issue by leonnicklas** [allexoK/Esp32-Stick-Boards-Docs#6]
Hi there again:)

I have already multiple boards of yours in use and I'm very happy with it!
Thanks for that already:)

I still have a question though:
Is it possible to get easy access to the PoE power on the board?

I know I can't pull to much current over PoE but for small components - which will not work on 3.3V or 5V - it could be very beneficial to get access to the PoE power itself before it gets converted down.

I couldn't find the information I'm looking for in your schematics, maybe you could help me out here again and point me in the right direction?

best regards
Leon

**Comment by allexoK** [comment]
Hi Leon, thanks!
I assume you are talking about the Passive PoE version. There are no PoE pins on the board, but you can get the PoE voltage from the diode bridge pads(You can get the GND from elsewhere):
![Screenshot from 2024-09-09 17-09-45](https://github.com/user-attachments/assets/72168290-9d35-4055-a798-464c8b7fb386)
Just solder the wires to the bridge pads.
With PoE-A there is some active communication between the PoE source and Esp32-Stick, so I'am not sure it would work....
Best regards,
Alex

**Comment by leonnicklas** [comment]
Thank's so much, that's exactly what I wanted to achieve! 🙏🏼

Best regards 
Leon

**Comment by leonnicklas** [comment]
@allexoK I again have a question for you: Can you give me the maximum ampere ratings for this diode bridge? I can't find the exact one's datasheet:/ Or is the rating just 0.5A? 

Best regards
Leon

**Comment by allexoK** [comment]
Hello @leonnicklas, Sure, I was using MB10S, here is [the exact datasheet](https://github.com/user-attachments/files/17481023/PDF.js.viewer.pdf)
Best regards,
Alex
